### ISSUE TITLE
Suggest correct usage of shebang

### ISSUE THREAD

**Issue by HarshCasper** [ahmadawais/create-node-cli#2]
## Description 

I have run a DeepSource Static Code Analysis on this Repository, the details of which are available [here](https://deepsource.io/gh/HarshCasper/create-node-cli/), and found the inappropriate use of shebang in the `template/_index.js` file.

This file needs no shebang according to the Static Code Analysis Tool.

**Comment by ahmadawais** [comment]
The file is a template and does need a shebang. This automated issue is a waste of maintainers time.
