### ISSUE TITLE
Migrate to ES6

### ISSUE THREAD

**Issue by Bam92** [ahmadawais/create-node-cli#8]
I tried to read the code base and notice that you are using `require`s, I'd like to migrate to ES6 with `import`.

**Comment by mikeerickson** [comment]
Not sure what advantage you are looking for by using ES6 imports, using commonJS require is completely acceptable for all CLIs using node?

If using ES6 imports/exports, a separate build process would be necessary, which is really not worth the overhead. 

I am curious why you feel this would be and improvement over what this project provides?

**Comment by Bam92** [comment]
Thank you for clarifications. It's just clear that there's not at all any advantage for that in CLIs apps.
